/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ObjectsObjectIdRouteImport } from './routes/objects.$objectId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ObjectsObjectIdRoute = ObjectsObjectIdRouteImport.update({
  id: '/objects/$objectId',
  path: '/objects/$objectId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/objects/$objectId': typeof ObjectsObjectIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/objects/$objectId': typeof ObjectsObjectIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/objects/$objectId': typeof ObjectsObjectIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/objects/$objectId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/objects/$objectId'
  id: '__root__' | '/' | '/objects/$objectId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ObjectsObjectIdRoute: typeof ObjectsObjectIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/objects/$objectId': {
      id: '/objects/$objectId'
      path: '/objects/$objectId'
      fullPath: '/objects/$objectId'
      preLoaderRoute: typeof ObjectsObjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ObjectsObjectIdRoute: ObjectsObjectIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
