"""add object image and references

Revision ID: 1fc1e2b8d872
Revises: 51c7cd53ada7
Create Date: 2026-08-20 21:31:24.403987

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "1fc1e2b8d872"
down_revision: str | None = "51c7cd53ada7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "object_references",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("object_id", sa.Uuid(), nullable=False),
        sa.Column("label", sa.String(), nullable=False),
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["object_id"], ["objects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("objects", sa.Column("image_url", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("objects", "image_url")
    op.drop_table("object_references")
    # ### end Alembic commands ###
