"""index objects by canonical latex and index every foreign key

Revision ID: 46a1b630e1f4
Revises: 1fc1e2b8d872
Create Date: 2026-08-27 20:01:26.014391

"""

from collections.abc import Sequence

from alembic import op

revision: str = "46a1b630e1f4"
down_revision: str | None = "1fc1e2b8d872"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_implementations_operator_id"), "implementations", ["operator_id"], unique=False
    )
    op.create_index(
        op.f("ix_object_references_object_id"), "object_references", ["object_id"], unique=False
    )
    op.create_index(op.f("ix_objects_latex"), "objects", ["latex"], unique=True)
    op.create_index(
        op.f("ix_relation_input_object_id"), "relation_input", ["object_id"], unique=False
    )
    op.create_index(
        op.f("ix_relation_input_relation_id"), "relation_input", ["relation_id"], unique=False
    )
    op.create_index(
        op.f("ix_relation_output_object_id"), "relation_output", ["object_id"], unique=False
    )
    op.create_index(
        op.f("ix_relation_output_relation_id"), "relation_output", ["relation_id"], unique=False
    )
    op.create_index(op.f("ix_relations_operator_id"), "relations", ["operator_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_relations_operator_id"), table_name="relations")
    op.drop_index(op.f("ix_relation_output_relation_id"), table_name="relation_output")
    op.drop_index(op.f("ix_relation_output_object_id"), table_name="relation_output")
    op.drop_index(op.f("ix_relation_input_relation_id"), table_name="relation_input")
    op.drop_index(op.f("ix_relation_input_object_id"), table_name="relation_input")
    op.drop_index(op.f("ix_objects_latex"), table_name="objects")
    op.drop_index(op.f("ix_object_references_object_id"), table_name="object_references")
    op.drop_index(op.f("ix_implementations_operator_id"), table_name="implementations")
    # ### end Alembic commands ###
