"""initial schema

Revision ID: 51c7cd53ada7
Revises:
Create Date: 2026-08-20 13:09:33.430565

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "51c7cd53ada7"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "objects",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("latex", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "implementations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("operator_id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(["operator_id"], ["objects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "operator_displays",
        sa.Column("operator_id", sa.Uuid(), nullable=False),
        sa.Column("template", sa.String(), nullable=True),
        sa.Column("hidden_by_default", sa.Boolean(), nullable=False),
        sa.Column("is_membership", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["operator_id"], ["objects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("operator_id"),
    )
    op.create_table(
        "relations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("operator_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["operator_id"], ["objects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "top_level_objects",
        sa.Column("object_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["object_id"], ["objects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("object_id"),
    )
    op.create_table(
        "relation_input",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("relation_id", sa.Uuid(), nullable=False),
        sa.Column("object_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["object_id"],
            ["objects.id"],
        ),
        sa.ForeignKeyConstraint(["relation_id"], ["relations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "relation_output",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("relation_id", sa.Uuid(), nullable=False),
        sa.Column("object_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["object_id"],
            ["objects.id"],
        ),
        sa.ForeignKeyConstraint(["relation_id"], ["relations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("relation_output")
    op.drop_table("relation_input")
    op.drop_table("top_level_objects")
    op.drop_table("relations")
    op.drop_table("operator_displays")
    op.drop_table("implementations")
    op.drop_table("objects")
    # ### end Alembic commands ###
