"""add description and top_level_objects

Revision ID: 88932076788a
Revises: 6b45813dddd2
Create Date: 2026-08-15 22:57:40.421248

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = '88932076788a'
down_revision: str | None = '6b45813dddd2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('top_level_objects',
    sa.Column('object_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['object_id'], ['objects.id'], ),
    sa.PrimaryKeyConstraint('object_id')
    )
    op.add_column('objects', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('objects', 'description')
    op.drop_table('top_level_objects')
    # ### end Alembic commands ###
